#include "MenuPageItemDefinition.h"

FMenuPageItemDefinition::FMenuPageItemDefinition() {
    this->_targetPlatforms = 0;
    this->_isEditorOnly = false;
    this->_itemType = EMenuPageItemType::PMIT_Undefined;
    this->_subPageDefinition = NULL;
    this->_selectionInputDelay = 0.00f;
    this->_multiOptionAutoGenerated = false;
    this->_progressDisplayValueMinimum = 0.00f;
    this->_progressDisplayValueMaximum = 0.00f;
    this->_progressIncrement = 0.00f;
}

