#pragma once
#include "CoreMinimal.h"
#include "EInputType.generated.h"

UENUM(BlueprintType)
enum class EInputType : uint8 {
    Undefined,
    LeftStick_Left,
    LeftStick_Right,
    LeftStick_Up,
    LeftStick_Down,
    LeftStick_Diagonal_LeftUp,
    LeftStick_Diagonal_LeftDown,
    LeftStick_Diagonal_RightUp,
    LeftStick_Diagonal_RightDown,
    LeftStick_EighthCircle_CW,
    LeftStick_EighthCircle_CCW,
    LeftStick_QuarterCircle_CW,
    LeftStick_QuarterCircle_CCW,
    LeftStick_HalfCircle_CW,
    LeftStick_HalfCircle_CCW,
    LeftStick_Arc_CW,
    LeftStick_Arc_CCW,
    LeftStick_Released,
    LeftStick_Released_Left,
    LeftStick_Released_Right,
    LeftStick_LAST,
    RightStick_Left = 50,
    RightStick_Right,
    RightStick_Up,
    RightStick_Down,
    RightStick_Diagonal_LeftUp,
    RightStick_Diagonal_LeftDown,
    RightStick_Diagonal_RightUp,
    RightStick_Diagonal_RightDown,
    RightStick_EighthCircle_CW,
    RightStick_EighthCircle_CCW,
    RightStick_QuarterCircle_CW,
    RightStick_QuarterCircle_CCW,
    RightStick_HalfCircle_CW,
    RightStick_HalfCircle_CCW,
    RightStick_Arc_CW,
    RightStick_Arc_CCW,
    RightStick_Released,
    RightStick_Released_Left,
    RightStick_Released_Right,
    RightStick_LAST,
    Trigger_Left_Full = 100,
    Trigger_Right_Full,
    Trigger_LAST,
};

